// Using global variables THREE, ForceGraph3D, and SpriteText from CDN script tags
export class Renderer3D {
    constructor(containerElement) {
        this.container = containerElement;
        this.instance = null;
        this.hoverNode = null;
        this.onNodeHoverCallback = null;
    }

    init(graphData) {
        // Ensure container has dimensions
        const w = this.container.clientWidth || window.innerWidth;
        const h = this.container.clientHeight || window.innerHeight;

        this.instance = ForceGraph3D()(this.container)
            .width(w)
            .height(h)
            .graphData(graphData)
            .backgroundColor('#0d0d12') // Deep dark background
            .nodeResolution(32)
            
            // 3-Tier Visual Hierarchy
            .nodeThreeObject(node => {
                const group = new THREE.Group();

                // 1. Geometry based on Type
                let geometry, material;
                
                // Color mapping by Community (generated by GraphMath)
                const hue = (node.community * 137.508) % 360;
                let colorStr = `hsl(${hue}, 80%, 60%)`;
                
                if (node.type === 'category') {
                    geometry = new THREE.BoxGeometry(10, 10, 10);
                    material = new THREE.MeshBasicMaterial({ color: '#ffffff', transparent: true, opacity: 0.9 });
                } else if (node.type === 'tag') {
                    // Octahedron for Tags, size based on how many users have it
                    const size = Math.min(Math.max(node.size * 1.5, 3), 15);
                    geometry = new THREE.OctahedronGeometry(size);
                    material = new THREE.MeshBasicMaterial({ color: colorStr, transparent: true, opacity: 0.8 });
                } else {
                    // Sphere for Users
                    const size = Math.max(node.degree * 2, 4);
                    geometry = new THREE.SphereGeometry(size);
                    // Admins are Cyan, Students are standard
                    const uColor = node.group === 'admin' ? '#00f0ff' : '#8888aa';
                    material = new THREE.MeshBasicMaterial({ color: uColor });
                }

                const mesh = new THREE.Mesh(geometry, material);
                group.add(mesh);

                // 2. SpriteText for Labels (LOD logic will handle visibility in render loop)
                try {
                    const sprite = new SpriteText(node.name || 'Unknown');
                    sprite.color = node.type === 'category' ? '#ffffff' : (node.type === 'tag' ? colorStr : '#aaaaaa');
                    sprite.textHeight = node.type === 'category' ? 12 : (node.type === 'tag' ? Math.max(node.size, 4) : 4);
                    
                    // Professional Clean Text Styling
                    sprite.backgroundColor = 'transparent';
                    sprite.borderColor = 'transparent';
                    sprite.strokeWidth = 0; // Remove stroke completely for clean minimalist look
                    sprite.fontWeight = node.type === 'category' ? 'bold' : 'normal';
                    sprite.fontFace = '"Inter", "Segoe UI", sans-serif'; // Modern font
                    
                    // Position label dynamically so it NEVER overlaps with the node
                    if (node.type === 'category') {
                        sprite.position.y = 12; // Above the 10x10 cube
                    } else if (node.type === 'tag') {
                        sprite.position.y = (Math.min(Math.max(node.size * 1.5, 3), 15)) + 4; // Above the octahedron
                    } else {
                        const s = Math.max(node.degree * 2, 4);
                        sprite.position.y = -(s + 5); // Below the sphere
                    }
                    
                    // Save reference to toggle visibility later
                    node.__sprite = sprite;
                    group.add(sprite);
                } catch(e) {}

                return group;
            })
            
            // Edge Styling based on Type
            .linkColor(link => link.color || 'rgba(255,255,255,0.2)')
            .linkWidth(link => link.weight || 0.5)
            
            // Interactivity
            .onNodeHover(node => {
                this.container.style.cursor = node ? 'pointer' : null;
                this.hoverNode = node;
                if (this.onNodeHoverCallback) this.onNodeHoverCallback(node);
            })
            .onNodeDragEnd(node => {
                node.fx = node.x;
                node.fy = node.y;
                node.fz = node.z;
            })
            .onNodeClick(node => {
                // Focus camera on double click (simulated by fast single click logic or just click)
                const distance = 80;
                const distRatio = 1 + distance/Math.hypot(node.x, node.y, node.z);
                this.instance.cameraPosition(
                    { x: node.x * distRatio, y: node.y * distRatio, z: node.z * distRatio },
                    node,
                    1500
                );
            });

        // Advanced Physics (Barnes-Hut, Collision, Repulsion)
        this.instance.d3Force('charge').strength(-300); // Strong repulsion
        this.instance.d3Force('link').distance(link => {
            if (link.type === 'BelongCategory') return 150;
            if (link.type === 'HasTag') return 80;
            return 50;
        });
        
        // Level of Detail (LOD) check every frame
        this.instance.onEngineTick(() => {
            const camPos = this.instance.cameraPosition();
            const graphData = this.instance.graphData();
            
            graphData.nodes.forEach(node => {
                if(node.__sprite) {
                    const dist = Math.hypot(node.x - camPos.x, node.y - camPos.y, node.z - camPos.z);
                    // Show categories always, tags if < 500, users if < 200
                    let visible = false;
                    if(node.type === 'category') visible = true;
                    else if(node.type === 'tag' && dist < 600) visible = true;
                    else if(node.type === 'user' && dist < 300) visible = true;
                    
                    // Also always show if hovered
                    if (this.hoverNode && this.hoverNode.id === node.id) visible = true;
                    
                    node.__sprite.visible = visible;
                }
            });
        });

        window.addEventListener('resize', () => {
            if (this.instance) {
                this.instance.width(this.container.clientWidth);
                this.instance.height(this.container.clientHeight);
            }
        });
    }

    updateData(graphData) {
        if (this.instance) {
            this.instance.graphData(graphData);
        }
    }
    
    onNodeHover(callback) {
        this.onNodeHoverCallback = callback;
    }
}
